name: Frontend Infrastructure

on:
  workflow_dispatch: # run manually when needed

jobs:
  infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Storage Account
        run: |
          az storage account create \
            --name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --location eastus \
            --sku Standard_LRS \
            --kind StorageV2

      - name: Enable Static Website Hosting
        run: |
          az storage blob service-properties update \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --static-website \
            --index-document index.html \
            --404-document index.html

      - name: Show Static Site URL
        run: |
          echo "Your static site is at:"
          echo "https://${{ secrets.AZURE_STORAGE_ACCOUNT }}.z13.web.core.windows.net"
